import Head from 'next/head'
import Image from 'next/image'
import {useState} from 'react'
import Menu from '../components/Menu'
import api from '../pages/api/api'
import {useRouter} from 'next/router'
import styles from '../styles/Autor.module.css'

export default function Cadastraa() {
  const [form , setForm] = useState ({});
  function handleInputChange(e) {
    const {id, value} = e.target
    setForm({ ...form, [id]: value });
  }
  console.log(form);
  const router = useRouter()
  async function handleSubmit (e) {
    e.preventDefault()
    const data = {
      nome: form.nome,
      sobrenome: form.sobrenome,
      datanascimento: form.data,
    }
    console.log(data)
    const autor_response = await api.post ('/inserir', data)
    console.log(autor_response);
    router.push('/')
  }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Cadastrar autor</title>Will
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
			<Menu />
      <main className={styles.main}>

        <div className={styles.livro}><p><img src="/images/autor.jpg" height={700} 
    width={730}/></p></div>

        <form onSubmit={handleSubmit}>
    <div className={styles.formulario}>
      FAÇA O CADASTRO DO AUTOR
    <div>
        <label for="nome">Nome: <br/></label>
        <input className={styles.box2} type="text" id="nome" onChange= {handleInputChange} value = {form.nome}/>
    </div>
    
    <div>
        <label for="sobrenome">Sobrenome: <br/></label>
        <input className={styles.box2} type="text" id="sobrenome" onChange= {handleInputChange} value = {form.sobrenome}/>
    </div>
    <div>
        <label for="date">Data de nascimento: <br/></label>
        <input className={styles.box2} type="date" id="data" onChange= {handleInputChange} value = {form.data}/>
    </div>
    <br/>
    <button className={styles.cadastrarautor} type="submit">Cadastrar autor</button>
    
    </div>
</form>
        
      </main>

      
    </div>
  )
}
