import Head from 'next/head'
import Image from 'next/image'
import {useState} from 'react'
import Menu from '../components/Menu'
import api from '../pages/api/api'
import {useRouter} from 'next/router'
import styles from '../styles/Cadastro.module.css'

export default function Cadastrol() {
  const [form , setForm] = useState ({});
  function handleInputChange(e) {
    const {id, value} = e.target
    setForm({ ...form, [id]: value });
  }
  console.log(form);
  const router = useRouter()
  async function handleSubmit (e) {
    e.preventDefault()
    const data = {
      nome: form.nome,
      autor: form.autor,
      editora: form.editora,
      datapublicacao: form.data,
      preco: form.preco,
    }
    console.log(data)
    const autor_response = await api.post ('/inserir_livros', data)
    console.log(autor_response);
    router.push('/')
  }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Cadastrar livro</title>Will
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
			<Menu />
      <main className={styles.main}>

        <div className={styles.livro}><p><img src="/images/livro.jpg" height={700} 
    width={730}/></p></div>

        <form onSubmit={handleSubmit}>
    <div className={styles.formulario}>
      FAÇA O CADASTRO DO LIVRO
    <div>
        <label for="nome">Nome: <br/></label>
        <input className={styles.box} type="text" id="nome" onChange= {handleInputChange} value = {form.nome}/>
    </div>
    
    <div>
        <label for="autor">Autor: <br/></label>
        <input className={styles.box} type="text" id="autor" onChange= {handleInputChange} value = {form.autor}/>
    </div>
    <div>
        <label for="datapublicacao">Data de publicação: <br/></label>
        <input className={styles.box} type="date" id="data" onChange= {handleInputChange} value ={form.data}/>
    </div>
    <div>
        <label for="editora">Editora: <br/></label>
        <input className={styles.box} type="text" id="editora" onChange= {handleInputChange} value = {form.editora}/>
    </div>
    <div>
        <label for="preco">Preço: <br/></label>
        <input className={styles.box} type="number" id="preco" onChange= {handleInputChange} value = {form.preco}/>
    </div>
    <br/>
    <button className={styles.cadastrarlivro} type="submit">Cadastrar livro</button>
    
    </div>
</form>
        
      </main>

      
    </div>
  )
}
