import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Menu from '../components/Menu'

import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ALS Biblioteca</title>Will
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/livroo.png" />
      </Head>
			<Menu />
      <main className={styles.main}>
        
     <div className={styles.esta}><p><img src="/images/estante.jpg" height={730} 
    width={1347}/></p></div>
        <div className={styles.textotitulo}><h1>ALS Biblioteca</h1></div>
        <div className={styles.textosec}>Seja bem-vindo á melhor biblioteca da internet</div>
        <Link href="/listagemLivro">
          <button className={styles.livros} type="button">Livros</button>
        </Link>
        <Link href="/listagemAutor">
          <button className={styles.autores} type="button">Autores</button>
        </Link>
      </main>

      <footer className={styles.footer}>
          Powered by Vercel
            and Replit
        
      </footer>
    </div>
  )
}
