import Menu from '../components/Menu.js'
import Head from 'next/head'
import api from './api/api'
import ListagemAutor from '/components/CardAutor.js'

export async function getServerSideProps() {
  const response = await api.get ('/')
    console.log(response.data);
  const autor = response.data;
  return {
    props: {
      autor
    }
  }
}

 export default function listarAutor({autor}) {
   return (
     <div>
       <Head>
        <title>ALS Biblioteca</title>Will
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />
      <div>
       {
         autor.map(listar => {
           return(
             <div key={listar.id}>
               <ListagemAutor  nome={listar.nome}  sobrenome={listar.sobrenome} data={listar.data_de_nascimento} id={listar.id} /> 
               </div>
           )
         })
       }
        </div>
     </div>
   )
 }