import Menu from '../components/Menu.js'
import Head from 'next/head'
import api from './api/api'
import ListagemLivro from '/components/CardLivro.js'

export async function getServerSideProps() {
  const response = await api.get ('/livros')
    console.log(response.data);
  const livro = response.data;
  return {
    props: {
      livro
    }
  }
}

 export default function listarLivro({livro}) {
   return (
     <div>
       <Head>
        <title>ALS Biblioteca</title>Will
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />
      <div>
       {
         livro.map(lista => {
           return(
             <div key={lista.id}>
               <ListagemLivro  nome={lista.nome}  autor={lista.autor} editora={lista.editora} data={lista.datapublicacao} preco={lista.preco} id={lista.id}/> 
               
               </div>
           )
         })
       }
        </div>
     </div>
   )
 }